CREATE TABLE IF NOT EXISTS "Application" (
	"ID"	INTEGER,
	"BinaryPath"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Host" (
	"ID"	INTEGER,
    "Family"  INTEGER NOT NULL CHECK (Family IN (4,6)),
	"IPAddress" BLOB NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Migration" (
	"Version"	INTEGER,
	"AppliedAt"	INTEGER NOT NULL DEFAULT (unixepoch()),
	PRIMARY KEY("Version")
);
CREATE TABLE "TrafficEvent" (
	"ID"	INTEGER,
	"SnapshotID"	INTEGER NOT NULL,
	"ItemID"	INTEGER NOT NULL,
	"HostID"	INTEGER NOT NULL,
	"BytesIn"	INTEGER NOT NULL,
	"BytesOut"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("HostID") REFERENCES "Host"("ID"),
	FOREIGN KEY("ItemID") REFERENCES "TrafficItem"("ID"),
	FOREIGN KEY("SnapshotID") REFERENCES "TrafficSnapshot"("ID")
);
CREATE TABLE IF NOT EXISTS "TrafficSnapshot" (
	"ID"	INTEGER,
	"Start"	INTEGER DEFAULT (unixepoch()),
	PRIMARY KEY("ID")
);
