CREATE TABLE IF NOT EXISTS "ConnectionHistoryEntry" (
	"ID"	INTEGER,
	"ItemID"	INTEGER NOT NULL,
	"RemoteHostID"	INTEGER NOT NULL,
	"StartTime"	INTEGER NOT NULL,
	"EndTime"	INTEGER NOT NULL,
	"DataIn"	INTEGER NOT NULL DEFAULT 0,
	"DataOut"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ItemID") REFERENCES "TrafficItem"("ID"),
	FOREIGN KEY("RemoteHostID") REFERENCES "Host"("ID")
);