CREATE TABLE IF NOT EXISTS "Rule" (
	"ID"	INTEGER,
	"Target"	TEXT NOT NULL,
	"UploadLimit"	INTEGER NOT NULL DEFAULT 0,
	"DownloadLimit"	INTEGER NOT NULL DEFAULT 0,
	"UploadSwitchState"	INTEGER NOT NULL DEFAULT 0,
	"DownloadSwitchState"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID")
);