CREATE TABLE IF NOT EXISTS "Asn" (
	"ID"	INTEGER,
	"Number"	INTEGER NOT NULL,
	"Organization"	TEXT NOT NULL,
	"Country"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
ALTER TABLE "Host" ADD COLUMN "AsnID" INTEGER;
ALTER TABLE "Host" ADD FOREIGN KEY("AsnID") REFERENCES "Asn"("ID");
