// Generated by MakeAtlas.py
#pragma once
#include <unordered_map>
#include <string>
#include <utility>
#include <glad/glad.h>
#include <imgui.h>

#include "Singleton.hpp"

extern std::unordered_map<std::string, std::pair<ImVec2, ImVec2>> const ICON_ATLAS_UV;

class WIconAtlas final : public TSingleton<WIconAtlas>
{
public:
	GLuint IconAtlasTextureId{ 0 };
	GLuint LogoTextureId{ 0 };
	void   Load();
	void   Unload();

	void DrawIcon(std::string const& Name, ImVec2 Size) const
	{
		auto const It = ICON_ATLAS_UV.find(Name);
		if (It == ICON_ATLAS_UV.end())
		{
			return;
		}

		ImGui::Image(IconAtlasTextureId, Size, It->second.first, It->second.second);
	}
};