/*
 * Copyright (c) 2025, Alex <uni@vrsal.xyz>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Generated by MakeAtlas.py
#pragma once
#include <unordered_map>
#include <string>
#include <utility>
#include <glad/glad.h>
#include <imgui.h>

#include "Singleton.hpp"
#include "Util/ImageUtil.hpp"

extern std::unordered_map<std::string, std::pair<ImVec2, ImVec2>> const ICON_ATLAS_UV;

class WIconAtlas final : public TSingleton<WIconAtlas>
{
public:
	WTexture IconAtlas{};
	WTexture Logo{};
	void     Load();
	void     Unload();

	bool DrawIconButton(char const* Id, std::string const& Name, ImVec2 const& Size, bool bNoBackground = true) const
	{
		auto const It = ICON_ATLAS_UV.find(Name);
		if (It == ICON_ATLAS_UV.end())
		{
			return false;
		}

		static ImVec4 const transparent(0.0f, 0.0f, 0.0f, 0.0f);
		if (bNoBackground)
		{
			// Remove frame padding and force transparent button colors to avoid visible background/hover rects
			ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));
			ImGui::PushStyleColor(ImGuiCol_Button, transparent);
			ImGui::PushStyleColor(ImGuiCol_ButtonActive, transparent);

			bool const Result = ImGui::ImageButton(Id, IconAtlas.TextureId, Size, It->second.first, It->second.second,
				transparent, ImVec4(1.0f, 1.0f, 1.0f, 1.0f));

			ImGui::PopStyleColor(2);
			ImGui::PopStyleVar();
			return Result;
		}

		// Default behavior (with standard styling)
		return ImGui::ImageButton(Id, IconAtlas.TextureId, Size, It->second.first, It->second.second);
	}

	void DrawIconTint(std::string const& Name, ImVec2 const& Size, ImColor const& Tint = ImColor(1, 1, 1, 1),
		ImColor Bg = ImColor(0, 0, 0, 0)) const
	{
		auto const It = ICON_ATLAS_UV.find(Name);
		if (It == ICON_ATLAS_UV.end())
		{
			return;
		}

		ImGui::ImageWithBg(IconAtlas.TextureId, Size, It->second.first, It->second.second, Bg, Tint);
	}

	void DrawIcon(std::string const& Name, ImVec2 Size) const
	{
		auto const It = ICON_ATLAS_UV.find(Name);
		if (It == ICON_ATLAS_UV.end())
		{
			return;
		}

		ImGui::Image(IconAtlas.TextureId, Size, It->second.first, It->second.second);
	}
};