#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -d /run/systemd/system ]; then
        if systemctl is-active --quiet waechterd.service; then
            systemctl stop waechterd.service || true
        fi
        systemctl disable waechterd.service || true
    fi
fi

exit 0
