BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ConnectionHistoryEntry" (
	"ID"	INTEGER,
	"ItemID"	INTEGER NOT NULL,
	"RemoteHostID"	INTEGER NOT NULL,
	"StartTime"	INTEGER NOT NULL,
	"EndTime"	INTEGER NOT NULL,
	"DataIn"	INTEGER NOT NULL DEFAULT 0,
	"DataOut"	INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY("ItemID") REFERENCES "TrafficItem"("ID"),
	FOREIGN KEY("RemoteHostID") REFERENCES "Host"("ID")
);
CREATE TABLE IF NOT EXISTS "Host" (
	"ID"	INTEGER,
	"IPAddress"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Migration" (
	"Version"	INTEGER,
	"AppliedAt"	INTEGER NOT NULL DEFAULT (unixepoch()),
	PRIMARY KEY("Version")
);
CREATE TABLE IF NOT EXISTS "TrafficEvent" (
	"ID"	INTEGER,
	"SnapshotID"	INTEGER NOT NULL,
	"ItemID"	INTEGER NOT NULL,
	"HostID"	INTEGER,
	"BytesIn"	INTEGER NOT NULL,
	"BytesOut"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("HostID") REFERENCES "Host"("ID"),
	FOREIGN KEY("ItemID") REFERENCES "TrafficItem"("ID"),
	FOREIGN KEY("SnapshotID") REFERENCES "TrafficSnapshot"("ID")
);
CREATE TABLE IF NOT EXISTS "TrafficItem" (
	"ID"	INTEGER,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "TrafficSnapshot" (
	"ID"	INTEGER,
	"Start"	INTEGER DEFAULT (unixepoch()),
	PRIMARY KEY("ID")
);
COMMIT;
