#pragma once

// generated by sqlite2cpp.py ./CurrentState.sql Schema Db::Schema

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace Db
{
namespace Schema
{
  namespace Host_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct IPAddress
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "IPAddress";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T IPAddress;
            T& operator()() { return IPAddress; }
            const T& operator()() const { return IPAddress; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Host_

  struct Host: sqlpp::table_t<Host,
               Host_::ID,
               Host_::IPAddress>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Host";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Host;
        T& operator()() { return Host; }
        const T& operator()() const { return Host; }
      };
    };
  };
  namespace Migration_
  {
    struct Version
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Version";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Version;
            T& operator()() { return Version; }
            const T& operator()() const { return Version; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct AppliedAt
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "AppliedAt";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T AppliedAt;
            T& operator()() { return AppliedAt; }
            const T& operator()() const { return AppliedAt; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace Migration_

  struct Migration: sqlpp::table_t<Migration,
               Migration_::Version,
               Migration_::AppliedAt>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Migration";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Migration;
        T& operator()() { return Migration; }
        const T& operator()() const { return Migration; }
      };
    };
  };
  namespace TrafficEvent_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct SnapshotID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "SnapshotID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T SnapshotID;
            T& operator()() { return SnapshotID; }
            const T& operator()() const { return SnapshotID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ItemID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ItemID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ItemID;
            T& operator()() { return ItemID; }
            const T& operator()() const { return ItemID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct HostID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "HostID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T HostID;
            T& operator()() { return HostID; }
            const T& operator()() const { return HostID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct BytesIn
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "BytesIn";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T BytesIn;
            T& operator()() { return BytesIn; }
            const T& operator()() const { return BytesIn; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct BytesOut
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "BytesOut";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T BytesOut;
            T& operator()() { return BytesOut; }
            const T& operator()() const { return BytesOut; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace TrafficEvent_

  struct TrafficEvent: sqlpp::table_t<TrafficEvent,
               TrafficEvent_::ID,
               TrafficEvent_::SnapshotID,
               TrafficEvent_::ItemID,
               TrafficEvent_::HostID,
               TrafficEvent_::BytesIn,
               TrafficEvent_::BytesOut>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficEvent";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficEvent;
        T& operator()() { return TrafficEvent; }
        const T& operator()() const { return TrafficEvent; }
      };
    };
  };
  namespace TrafficItem_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Name;
            T& operator()() { return Name; }
            const T& operator()() const { return Name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace TrafficItem_

  struct TrafficItem: sqlpp::table_t<TrafficItem,
               TrafficItem_::ID,
               TrafficItem_::Name>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficItem";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficItem;
        T& operator()() { return TrafficItem; }
        const T& operator()() const { return TrafficItem; }
      };
    };
  };
  namespace TrafficSnapshot_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Start
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Start";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Start;
            T& operator()() { return Start; }
            const T& operator()() const { return Start; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace TrafficSnapshot_

  struct TrafficSnapshot: sqlpp::table_t<TrafficSnapshot,
               TrafficSnapshot_::ID,
               TrafficSnapshot_::Start>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficSnapshot";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficSnapshot;
        T& operator()() { return TrafficSnapshot; }
        const T& operator()() const { return TrafficSnapshot; }
      };
    };
  };
} // namespace Schema
} // namespace Db
