#pragma once

// generated by sqlite2cpp.py ./CurrentState.sql Db::Schema

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace Db
{
namespace Schema
{
  namespace Asn_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Number
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Number";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Number;
            T& operator()() { return Number; }
            const T& operator()() const { return Number; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Organization
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Organization";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Organization;
            T& operator()() { return Organization; }
            const T& operator()() const { return Organization; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Country
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Country";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Country;
            T& operator()() { return Country; }
            const T& operator()() const { return Country; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Asn_

  struct Asn: sqlpp::table_t<Asn,
               Asn_::ID,
               Asn_::Number,
               Asn_::Organization,
               Asn_::Country>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Asn";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Asn;
        T& operator()() { return Asn; }
        const T& operator()() const { return Asn; }
      };
    };
  };
  namespace ConnectionHistoryEntry_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct ItemID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ItemID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ItemID;
            T& operator()() { return ItemID; }
            const T& operator()() const { return ItemID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct RemoteHostID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "RemoteHostID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T RemoteHostID;
            T& operator()() { return RemoteHostID; }
            const T& operator()() const { return RemoteHostID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Port
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Port";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Port;
            T& operator()() { return Port; }
            const T& operator()() const { return Port; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct StartTime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "StartTime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T StartTime;
            T& operator()() { return StartTime; }
            const T& operator()() const { return StartTime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct EndTime
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "EndTime";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T EndTime;
            T& operator()() { return EndTime; }
            const T& operator()() const { return EndTime; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct DataIn
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "DataIn";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T DataIn;
            T& operator()() { return DataIn; }
            const T& operator()() const { return DataIn; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct DataOut
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "DataOut";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T DataOut;
            T& operator()() { return DataOut; }
            const T& operator()() const { return DataOut; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace ConnectionHistoryEntry_

  struct ConnectionHistoryEntry: sqlpp::table_t<ConnectionHistoryEntry,
               ConnectionHistoryEntry_::ID,
               ConnectionHistoryEntry_::ItemID,
               ConnectionHistoryEntry_::RemoteHostID,
               ConnectionHistoryEntry_::Port,
               ConnectionHistoryEntry_::StartTime,
               ConnectionHistoryEntry_::EndTime,
               ConnectionHistoryEntry_::DataIn,
               ConnectionHistoryEntry_::DataOut>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "ConnectionHistoryEntry";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T ConnectionHistoryEntry;
        T& operator()() { return ConnectionHistoryEntry; }
        const T& operator()() const { return ConnectionHistoryEntry; }
      };
    };
  };
  namespace Host_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Family
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Family";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Family;
            T& operator()() { return Family; }
            const T& operator()() const { return Family; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct IPAddress
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "IPAddress";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T IPAddress;
            T& operator()() { return IPAddress; }
            const T& operator()() const { return IPAddress; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::blob, sqlpp::tag::require_insert>;
    };
    struct AsnID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "AsnID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T AsnID;
            T& operator()() { return AsnID; }
            const T& operator()() const { return AsnID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace Host_

  struct Host: sqlpp::table_t<Host,
               Host_::ID,
               Host_::Family,
               Host_::IPAddress,
               Host_::AsnID>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Host";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Host;
        T& operator()() { return Host; }
        const T& operator()() const { return Host; }
      };
    };
  };
  namespace Migration_
  {
    struct Version
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Version";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Version;
            T& operator()() { return Version; }
            const T& operator()() const { return Version; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct AppliedAt
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "AppliedAt";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T AppliedAt;
            T& operator()() { return AppliedAt; }
            const T& operator()() const { return AppliedAt; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace Migration_

  struct Migration: sqlpp::table_t<Migration,
               Migration_::Version,
               Migration_::AppliedAt>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Migration";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Migration;
        T& operator()() { return Migration; }
        const T& operator()() const { return Migration; }
      };
    };
  };
  namespace Rule_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Target
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Target";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Target;
            T& operator()() { return Target; }
            const T& operator()() const { return Target; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct UploadLimit
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "UploadLimit";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T UploadLimit;
            T& operator()() { return UploadLimit; }
            const T& operator()() const { return UploadLimit; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct DownloadLimit
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "DownloadLimit";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T DownloadLimit;
            T& operator()() { return DownloadLimit; }
            const T& operator()() const { return DownloadLimit; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct UploadSwitchState
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "UploadSwitchState";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T UploadSwitchState;
            T& operator()() { return UploadSwitchState; }
            const T& operator()() const { return UploadSwitchState; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct DownloadSwitchState
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "DownloadSwitchState";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T DownloadSwitchState;
            T& operator()() { return DownloadSwitchState; }
            const T& operator()() const { return DownloadSwitchState; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace Rule_

  struct Rule: sqlpp::table_t<Rule,
               Rule_::ID,
               Rule_::Target,
               Rule_::UploadLimit,
               Rule_::DownloadLimit,
               Rule_::UploadSwitchState,
               Rule_::DownloadSwitchState>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "Rule";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T Rule;
        T& operator()() { return Rule; }
        const T& operator()() const { return Rule; }
      };
    };
  };
  namespace TrafficEvent_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct SnapshotID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "SnapshotID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T SnapshotID;
            T& operator()() { return SnapshotID; }
            const T& operator()() const { return SnapshotID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ItemID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ItemID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ItemID;
            T& operator()() { return ItemID; }
            const T& operator()() const { return ItemID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct HostID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "HostID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T HostID;
            T& operator()() { return HostID; }
            const T& operator()() const { return HostID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct BytesIn
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "BytesIn";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T BytesIn;
            T& operator()() { return BytesIn; }
            const T& operator()() const { return BytesIn; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct BytesOut
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "BytesOut";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T BytesOut;
            T& operator()() { return BytesOut; }
            const T& operator()() const { return BytesOut; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace TrafficEvent_

  struct TrafficEvent: sqlpp::table_t<TrafficEvent,
               TrafficEvent_::ID,
               TrafficEvent_::SnapshotID,
               TrafficEvent_::ItemID,
               TrafficEvent_::HostID,
               TrafficEvent_::BytesIn,
               TrafficEvent_::BytesOut>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficEvent";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficEvent;
        T& operator()() { return TrafficEvent; }
        const T& operator()() const { return TrafficEvent; }
      };
    };
  };
  namespace TrafficItem_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Name;
            T& operator()() { return Name; }
            const T& operator()() const { return Name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace TrafficItem_

  struct TrafficItem: sqlpp::table_t<TrafficItem,
               TrafficItem_::ID,
               TrafficItem_::Name>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficItem";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficItem;
        T& operator()() { return TrafficItem; }
        const T& operator()() const { return TrafficItem; }
      };
    };
  };
  namespace TrafficSnapshot_
  {
    struct ID
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ID";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ID;
            T& operator()() { return ID; }
            const T& operator()() const { return ID; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct Start
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "Start";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T Start;
            T& operator()() { return Start; }
            const T& operator()() const { return Start; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace TrafficSnapshot_

  struct TrafficSnapshot: sqlpp::table_t<TrafficSnapshot,
               TrafficSnapshot_::ID,
               TrafficSnapshot_::Start>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "TrafficSnapshot";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T TrafficSnapshot;
        T& operator()() { return TrafficSnapshot; }
        const T& operator()() const { return TrafficSnapshot; }
      };
    };
  };
} // namespace Schema
} // namespace Db
